default_settings: null
behaviors:
  My Behavior:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 1 #lets just do one
      shared_critic: True #internet says that this is a good idea
      learning_rate_schedule: none #decreace as training happens
      beta_schedule: none #decreace as training happens
      epsilon_schedule: none #decreace as training happens
    network_settings:
      normalize: true #I feel like normalizing is always a good thing... this came to me in a dream
      hidden_units: 64
      num_layers: 1
      vis_encode_type: none
      memory: null
      goal_conditioning_type: none
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        # network_settings: unsure why this second set of network_settings is here, removing it for testing
          # normalize: false
          # hidden_units: 128
          # num_layers: 2
          # vis_encode_type: simple
          # memory: null
          # goal_conditioning_type: hyper
          # deterministic: false
    init_path: null
    keep_checkpoints: 5
    checkpoint_interval: 500000
    max_steps: 50000000
    time_horizon: 64
    summary_freq: 50000
    threaded: false
    self_play: null
    behavioral_cloning: null
# env_settings: dont think we need these either
#   env_path: null
#   env_args: null
#   base_port: 5005
#   num_envs: 60 #this might need to change. this is the number of paralell environments in my scene
#   num_areas: 1 #good
#   seed: -1
#   max_lifetime_restarts: 10
#   restarts_rate_limit_n: 1
#   restarts_rate_limit_period_s: 60
 engine_settings: #dont think we need these either
#   width: 84
#   height: 84
#   quality_level: 3
#   time_scale: 20
#   target_frame_rate: -1
#   capture_frame_rate: 60
   no_graphics: True #changed to true, we dont need this thing to see
environment_parameters: null
checkpoint_settings:
  run_id: PPO_edited_minimal
  initialize_from: null
  load_model: false
  resume: false
  force: false
  train_model: false
  inference: false
  results_dir: results
torch_settings:
  device: null
debug: false
