behaviors:
  SACBehavior:
    trainer_type: sac
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.0003
      learning_rate_schedule: none
      tau: 0.005
      steps_per_update: 10
      save_replay_buffer: false
      init_entcoef: 0.1
      use_continuous_act: False
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
      vis_encode_type: none
      memory: null
      goal_conditioning_type: none
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    init_path: null
    keep_checkpoints: 5
    checkpoint_interval: 500000
    max_steps: 5000000
    time_horizon: 64
    summary_freq: 10000
    threaded: false
    self_play: null
    behavioral_cloning: null
 engine_settings:
#   width: 84
#   height: 84
#   quality_level: 5
#   time_scale: 20
#   target_frame_rate: -1
#   capture_frame_rate: 60
   no_graphics: true
environment_parameters: null
checkpoint_settings:
  run_id: SAC_minimal
  initialize_from: null
  load_model: false
  resume: false
  force: false
  train_model: true
  inference: false
  results_dir: results
torch_settings:
  device: null
debug: false